/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio2;

import javax.swing.JLabel;

public class VueltoCliente extends javax.swing.JFrame {
    
    public static JLabel etiquetaDineroInsuficiente;
    public static JLabel etiquetaMontoExacto;

    /**
     * Creates new form VueltoCliente
     */
    public VueltoCliente() {
        initComponents();
        
        etiquetaDineroInsuficiente = lblAvisoDineroInsuficiente;
        etiquetaDineroInsuficiente.setVisible(false);
        etiquetaMontoExacto = lblAvisoMontoExacto;
        etiquetaMontoExacto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGraciasPorElegirnos = new javax.swing.JLabel();
        lblUstedIngreso = new javax.swing.JLabel();
        lblSuVueltoEs = new javax.swing.JLabel();
        lblCantidadBilletesVuelto = new javax.swing.JLabel();
        txtUstedIngreso = new javax.swing.JTextField();
        txtSuVueltoEs = new javax.swing.JTextField();
        txtCantidadBilletesVuelto = new javax.swing.JTextField();
        lblVuelvaPronto = new javax.swing.JLabel();
        lblAvisoDineroInsuficiente = new javax.swing.JLabel();
        btnSalirVuelto = new javax.swing.JButton();
        lblAvisoMontoExacto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vuelto correspondiente");

        lblGraciasPorElegirnos.setFont(new java.awt.Font("Blackadder ITC", 0, 27)); // NOI18N
        lblGraciasPorElegirnos.setText("¡Gracias por elegirnos!");

        lblUstedIngreso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUstedIngreso.setText("Usted ingresó:");

        lblSuVueltoEs.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSuVueltoEs.setText("El total de su vuelto es:");

        lblCantidadBilletesVuelto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCantidadBilletesVuelto.setText("Cantidad de billetes en su vuelto:");

        txtUstedIngreso.setEditable(false);

        txtSuVueltoEs.setEditable(false);

        txtCantidadBilletesVuelto.setEditable(false);

        lblVuelvaPronto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblVuelvaPronto.setText("¡Vuelva Pronto!");

        lblAvisoDineroInsuficiente.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lblAvisoDineroInsuficiente.setForeground(new java.awt.Color(102, 0, 0));
        lblAvisoDineroInsuficiente.setText("Dinero ingesado insuficiente. Por favor, ingrese el monto completo.");

        btnSalirVuelto.setText("SALIR");
        btnSalirVuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirVueltoActionPerformed(evt);
            }
        });

        lblAvisoMontoExacto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAvisoMontoExacto.setText("Usted ha pagado el monto exacto, por lo que no recibirá vuelto.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblVuelvaPronto)
                .addGap(74, 74, 74)
                .addComponent(btnSalirVuelto)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUstedIngreso)
                            .addComponent(lblCantidadBilletesVuelto)
                            .addComponent(lblSuVueltoEs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtUstedIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSuVueltoEs, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidadBilletesVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvisoDineroInsuficiente)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblGraciasPorElegirnos)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAvisoMontoExacto, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblGraciasPorElegirnos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUstedIngreso)
                    .addComponent(txtUstedIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSuVueltoEs)
                    .addComponent(txtSuVueltoEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadBilletesVuelto)
                    .addComponent(txtCantidadBilletesVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvisoDineroInsuficiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvisoMontoExacto)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirVuelto)
                    .addComponent(lblVuelvaPronto))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirVueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirVueltoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirVueltoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueltoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueltoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueltoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueltoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueltoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirVuelto;
    private javax.swing.JLabel lblAvisoDineroInsuficiente;
    private javax.swing.JLabel lblAvisoMontoExacto;
    private javax.swing.JLabel lblCantidadBilletesVuelto;
    private javax.swing.JLabel lblGraciasPorElegirnos;
    private javax.swing.JLabel lblSuVueltoEs;
    private javax.swing.JLabel lblUstedIngreso;
    private javax.swing.JLabel lblVuelvaPronto;
    private javax.swing.JTextField txtCantidadBilletesVuelto;
    private javax.swing.JTextField txtSuVueltoEs;
    private javax.swing.JTextField txtUstedIngreso;
    // End of variables declaration//GEN-END:variables
}
